name: Build
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /*
            !/docker-compose.yml
      - name: Prepare to build
        run: mv docker-compose-dev.yml docker-compose.yml
      - name: Run docker compose build
        run: sudo docker compose up -d --build